##
## GpLapTim TSR for MPS GP.EXE
##

ASM            =    tasm
ASM_FLAGS      =    -Ml -zd -zi -i..\inc
LINK           =    tlink /k /l /m /s /c /Tdc

OBJS           =    gplaptim.obj

.asm.obj:
               $(ASM) $< $(ASM_FLAGS),,;

all:           gplaptim.com

gplaptim.ash:  gplaptim.h
               h2ash gplaptim.h

gplaptim.obj:  gplaptim.asm gplaptim.ash

gplaptim.com:  $(OBJS) makefile
               $(LINK) $(OBJS),gplaptim;

buildall:      all
