##
## Computer Car's Pit Strategy Simulator
##

CC             =    bcc
CC_FLAGS       =    -c -v -1 -O2 -I..
LINK           =    bcc
LINK_FLAGS     =    -M -v

OBJS           =    ccpitsim.obj pit.obj

all:           ccpitsim.exe

pit.obj:       ../pit.c ../ccpit.h
               $(CC) $(CC_FLAGS) ../pit.c

ccpitsim.obj:  ccpitsim.c ../ccpit.h
			   $(CC) $(CC_FLAGS) ccpitsim.c

ccpitsim.exe:  $(OBJS) makefile
               $(LINK) $(LINK_FLAGS) $(OBJS)

buildall:      all

